name: Docker keyserver CI

on:
  push:
    branches: [master]
    paths-ignore:
      - 'native/**'
      - 'docs/**'
      - 'services/**'
      - 'desktop/**'
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      # - name: Build Docker
      #   working-directory: ./keyserver
      #   run: touch .env && bash/dc.sh build --no-cache
