name: macOS Build CI

on:
  workflow_call:
  push:
    branches: [master]
    paths-ignore:
      - 'landing/**'
      - 'docs/**'
      - 'keyserver/**'
      - 'native/**'
      - 'shared/**'

jobs:
  build:
    name: Build macOS app
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Install new node-gyp
      #   run: yarn global add node-gyp@10

      - name: sudo ./install_protobuf.sh
        working-directory: ./scripts
        run: sudo ./install_protobuf.sh

      - name: yarn ci-cleaninstall
        run: yarn ci-cleaninstall

      - name: Build App
        env:
          APPLE_USER_NAME: ${{secrets.APPLE_USER_NAME}}
          APPLE_APP_SPECIFIC_PASSWORD: ${{secrets.APPLE_APP_SPECIFIC_PASSWORD}}
          TEAM_ID: ${{secrets.TEAM_ID}}
        working-directory: './desktop'
        run: yarn make --arch universal
