name: Windows build CI

on:
  push:
    branches: [electron-general]
    paths-ignore:
      - 'landing/**'
      - 'docs/**'
      - 'keyserver/**'
      - 'native/**'
      - 'shared/**'
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Install Yarn
        run: npm install -g yarn

      - name: yarn --frozen-lockfile --network-timeout 180000
        run: yarn --frozen-lockfile --network-timeout 180000

      - name: Build App
        working-directory: './desktop'
        run: yarn make